[package]
name = "factorio-benchmark-helper"
version = "0.0.5"
authors = ["mulark <mulark11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
directories = "*"
rust-ini = "*"
textwrap = "*"
rusqlite = { version = "*", features = ["bundled"] }
glob = "*"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
reqwest = "*"
sha1 = "*"
sha2 = "*"
raw-cpuid = "*"
clap = "*"
nix = "*"
bincode = "*"

[profile.release]
debug = 1
