[package]
name = "factorio-benchmark-helper"
version = "0.1.2"
authors = ["mulark <mulark11@gmail.com>"]
edition = "2018"

[dependencies]
regex = "*"
directories = "*"
rust-ini = "*"
rusqlite = { version = "*", features = ["bundled"] }
glob = "*"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
reqwest = { version = "0.9.*"}
sha1 = "*"
sha2 = "*"
raw-cpuid = "*"
clap = "*"
bincode = "*"

[profile.release]
debug = 1
