[package]
name = "factorio_rust"
version = "0.0.1"
authors = ["mulark <mulark11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
directories = "2.0.2"
rust-ini = "0.13"
textwrap = "0.11"
getopts = "0.2"
rusqlite = "0.20"
glob = "0.3.0"
lazy_static = "1.4.0"

[profile.release]
debug = 1
