[package]
name = "factorio-benchmark-helper"
version = "0.0.2"
authors = ["mulark <mulark11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
directories = "2.0.2"
rust-ini = "0.13"
textwrap = "0.11"
getopts = "0.2"
rusqlite = "0.20"
glob = "0.3.0"
lazy_static = "1.4.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1"
reqwest = "0.9.22"
sha1 = "*"
sha2 = "*"
raw-cpuid = "*"

[profile.release]
debug = 1
